# Dependencies

highlighter:      rouge

plugins:
  - jemoji


# Setup
title:            pra-kri
tagline:          'Prabesh K'
description:      'Notebook: thoughts + essays + code on decision-making, uncertainty, and related areas.'
url:              https://pra-kri.github.io
baseurl:          /pra-kri.github.io/

author:
  name:           'P.K.'
  url:            https://github.com/pra-kri/pra-kri.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pra-kri/pra-kri.github.io
